# Generated by Django 2.0.4 on 2018-04-25 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='link',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='case',
            name='name',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='case',
            name='tag',
            field=models.CharField(max_length=50),
        ),
    ]
