# Generated by Django 2.0.4 on 2018-06-10 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facts', '0002_auto_20180426_0059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='link',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='case',
            name='name',
            field=models.CharField(max_length=250),
        ),
    ]
